### ISSUE TITLE
record logged in account/role in a file

### ISSUE THREAD

**Issue by byujol** [byu-oit/awslogin#11]
I would like to be able to add my last used account/role into my shell prompt for convenience. Something like:

PowerUser@prd-sim-appdev-oit-byu /opt/webroot$

I would like to be able to look somewhere or make a call to get the account and role information.

**Comment by bwinterton** [comment]
We can easily handle this by just having awslogin set an environment variable when the login is successful. Then we can just document that variable and @byujol would easily be able to include it in his prompt as well as anyone else who would like similar functionality. 

Also, considering his last point, it may be helpful to include like a `awslogin status` command which spits out what account/role combination is currently being used (or list all of them if multiple profiles have been populated).

**Comment by pauldeden** [comment]
+1

**Comment by bwinterton** [comment]
So, thinking about what @byujol has said, writing out to a file (such as a lock file or a socket) might be a better solution as that would persist across sessions and different terminals as exporting an environment variable would only persist for the current session/tty. Plus, a file is more accessible in other cases where it may be necessary for other automations (especially on windows). 

Another thing to note is that once again, a command added such as `status` could help interface against this file so that developers don't necessarily have to know where it is. Just more thoughts from Braydenland

**Comment by ndpete** [comment]
FYI - I have this done just waiting on direction on what process you'd like me to create the pull request since I no longer have write access to the repo. (Fork and create Pull request or have someone give me rights?)
I write the info to the config file like the old tool used to. I also wrote a --status command that prints a line out like the following for the default profile, a profile of your choosing, or all profiles:
Not showed in this preview is I also incorporated the coloring we've used before.
```sh
ndpete@Loki >> awslogin --status
PowerUser@trn-oit-byu - Expired at: 07-26-2017 12:02
ndpete@Loki >> awslogin --status
PowerUser@trn-oit-byu - Expires at: 07-26-2017 13:13
ndpete@Loki >> awslogin --status --profile all
default - PowerUser@trn-oit-byu - Expires at: 07-26-2017 13:13
profile tst - Couldn't find status info
TEST - Couldn't find status info
trn - Couldn't find status info
tst - PowerUser@dev-oit-byu - Expired at: 07-26-2017 12:04
```
