### ISSUE TITLE
Add a --version argument

### ISSUE THREAD

**Issue by pauldeden** [byu-oit/awslogin#14]
Most CLIs have a --version argument and it would be good to be able to easily check the version of awslogin.

It should work like this
`awslogin --version`

**Comment by ndpete** [comment]
Does anybody oppose me moving the Version number from the file Version to a property called `__version__` in the __init__.py of the Module so that is available at run time?
As an example the awscli does something similiar [here](https://github.com/aws/aws-cli/blob/develop/awscli/__init__.py)
And the PEP article that recommends something similar [here](https://www.python.org/dev/peps/pep-0396/)

Also as a side note I apparently can't assign this issue to myself for some reason.

**Comment by ndpete** [comment]
FYI - I have this done just waiting on direction on what process you'd like me to create the pull request since I no longer have write access to the repo.
