### ISSUE TITLE
Coloring doesn't show up on CLI

### ISSUE THREAD

**Issue by SicilyBennett** [byu-oit/awslogin#18]
This is what I see when I'm logging into AWS. The login works but the text coloring isn't working right:

![image](https://user-images.githubusercontent.com/31012201/29470071-31a44542-8408-11e7-8ca0-8727c2700a55.png)

Is this an issue with the latest version of awslogin or maybe because of python 6.0.2?

**Comment by pauldeden** [comment]
This happens because the windows Command Prompt doesn't support colors.  If you run `awslogin` in the PowerShell prompt or the Linux prompt on windows you will see the colors.

**Comment by SicilyBennett** [comment]
Interesting... I guess I'm using powershell then!

**Comment by pauldeden** [comment]
Let us know if that doesn't work and we'll look at this again.

**Comment by pauldeden** [comment]
Reopening to investigate if https://pypi.python.org/pypi/colorama will make this work on Windows without breaking colors on other platforms.

**Comment by ndpete** [comment]
I looked into colorama and it is very straight forward. However there is one existing bug both in colorama and python itself that breaks it slightly. That being it doesn't work when you use `input()` which our code uses 2-3 times. I've been unable to find a workaround better than just using powershell.

On further investigation it looks like windows added ansi color support to windows 10 but one of there updates disabled it for child process in the default cmd and not in powershell which is why this works in powershell (powershell and cmd are running in the same console) I have a proof of concept that is working and will have a pull request that fixes this soon.
